[build]
builder = "NIXPACKS"
buildCommand = "./gradlew clean build -x test"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar build/libs/careermap-backend-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
